version: '3.4'

services:
  # MongoDB Service
  mongodb:
    image: mongo:7.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  api:
    image: gameapi/rust:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8001:8000"
    environment:
      - APP_NAME=${APP_NAME}
      - APP_ALLOWED_SUBJ=${APP_ALLOWED_SUBJ}
      - APP_JWT_SIGNING_KEY=${APP_JWT_SIGNING_KEY}
      - APP_MONGO_CONNECTION_STRING=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/${MONGO_INITDB_DATABASE}?directConnection=true&authSource=admin
    depends_on:
      - mongodb

